name: Babel2
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cuda=13.1.1=ha63b06e_0
  - cuda-cccl_linux-64=13.1.115=0
  - cuda-command-line-tools=13.1.1=0
  - cuda-compiler=13.1.1=ha63b06e_0
  - cuda-crt-dev_linux-64=13.1.115=0
  - cuda-crt-tools=13.1.115=0
  - cuda-ctadvisor=13.1.115=h4f1e1d6_1
  - cuda-cudart=13.1.80=h6205011_0
  - cuda-cudart-dev=13.1.80=h3b4bcfc_0
  - cuda-cudart-dev_linux-64=13.1.80=hbe36340_0
  - cuda-cudart-static=13.1.80=h3b4bcfc_0
  - cuda-cudart-static_linux-64=13.1.80=hbe36340_0
  - cuda-cudart_linux-64=13.1.80=h61a3acf_0
  - cuda-cuobjdump=13.1.115=he32a221_0
  - cuda-cupti=13.1.115=h4f1e1d6_0
  - cuda-cupti-dev=13.1.115=he32a221_0
  - cuda-cuxxfilt=13.1.115=he32a221_0
  - cuda-driver-dev=13.1.80=h3b4bcfc_0
  - cuda-driver-dev_linux-64=13.1.80=hbe36340_0
  - cuda-gdb=13.1.115=h4f1e1d6_0
  - cuda-libraries=13.1.1=0
  - cuda-libraries-dev=13.1.1=0
  - cuda-nsight=13.1.115=hf678805_0
  - cuda-nvcc=13.1.115=h4e12aa9_0
  - cuda-nvcc-dev_linux-64=13.1.115=0
  - cuda-nvcc-impl=13.1.115=h74be60c_0
  - cuda-nvcc-tools=13.1.115=h4f1e1d6_0
  - cuda-nvcc_linux-64=13.1.115=h292b653_0
  - cuda-nvdisasm=13.1.115=he32a221_0
  - cuda-nvml-dev=13.1.115=he32a221_0
  - cuda-nvprune=13.1.115=he32a221_0
  - cuda-nvrtc=13.1.115=he32a221_0
  - cuda-nvrtc-dev=13.1.115=he32a221_0
  - cuda-nvtx=13.1.115=h4f1e1d6_0
  - cuda-nvvm-dev_linux-64=13.1.115=0
  - cuda-nvvm-impl=13.1.115=h09b770d_0
  - cuda-nvvm-tools=13.1.115=h09b770d_0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-opencl-dev=13.1.115=h4f1e1d6_0
  - cuda-profiler-api=13.1.115=hf678805_0
  - cuda-runtime=13.1.1=ha63b06e_0
  - cuda-sanitizer-api=13.1.118=hc1e0326_0
  - cuda-tileiras=13.1.80=h4f1e1d6_1
  - cuda-toolkit=13.1.1=ha63b06e_0
  - cuda-tools=13.1.1=0
  - cuda-version=13.1=hd92462c_3
  - cuda-visual-tools=13.1.1=0
  - cupy=13.6.0=py311h3416b12_2
  - cupy-core=13.6.0=py311h2124c9d_2
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - fastrlock=0.8.3=py311hc665b79_2
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - gcc_impl_linux-64=15.2.0=h36674fd_7
  - gcc_linux-64=15.2.0=h1ca4c6b_12
  - gds-tools=1.16.1.26=h2e6a4e3_0
  - gmp=6.3.0=h6a678d5_0
  - gxx_impl_linux-64=15.2.0=h6e002af_7
  - gxx_linux-64=15.2.0=h94d4220_12
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=13.2.1.1=h0bdde2c_0
  - libcublas-dev=13.2.1.1=h0bdde2c_0
  - libcufft=12.1.0.78=h6fb6d45_0
  - libcufft-dev=12.1.0.78=h6fb6d45_0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcufile-dev=1.16.1.26=h2e6a4e3_0
  - libcurand=10.4.1.81=h1b6c897_0
  - libcurand-dev=10.4.1.81=h1b6c897_0
  - libcusolver=12.0.9.81=hfcec1d2_0
  - libcusolver-dev=12.0.9.81=hfcec1d2_0
  - libcusparse=12.7.3.1=h693dda1_0
  - libcusparse-dev=12.7.3.1=h693dda1_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=hcb64138_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libllvm20=20.1.8=h465586c_0
  - libnpp=13.0.3.3=hcc83568_0
  - libnpp-dev=13.0.3.3=hcc83568_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvfatbin=13.1.115=he32a221_0
  - libnvfatbin-dev=13.1.115=he32a221_0
  - libnvjitlink=13.1.115=he32a221_0
  - libnvjitlink-dev=13.1.115=he32a221_0
  - libnvjpeg=13.0.3.75=h06761be_0
  - libnvjpeg-dev=13.0.3.75=h0b38513_0
  - libnvptxcompiler-dev=13.1.115=0
  - libnvptxcompiler-dev_linux-64=13.1.115=0
  - libopengl=1.7.0=h5eee18b_2
  - libpng=1.6.50=h2ed474d_0
  - libsanitizer=15.2.0=h56912e6_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=hcb64138_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.46.0=py311ha853ca8_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2025.4.1.2=h6f129cd_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numba=0.63.1=py311hbd3cbf0_0
  - numpy=1.26.4=py311h64c44e4_1
  - numpy-base=1.26.4=py311he1678cf_1
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.14=h6fa692b_0
  - python_abi=3.11=2_cp311
  - readline=8.3=hc2a1206_0
  - scipy=1.16.3=py311h33bc11c_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.45.1=py311h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - babelviscofdtd==1.2.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.61.1
      - h5py==3.15.1
      - hdf5plugin==6.0.0
      - histoprint==2.6.0
      - idna==3.11
      - imageio==2.37.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linetimer==0.1.5
      - manifold3d==3.2.1
      - matplotlib==3.7.1
      - networkx==3.6.1
      - nibabel==5.2.1
      - numpy-stl==3.0.1
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==1.5.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - pwlf==2.5.2
      - pydicom==3.0.1
      - pygments==2.19.2
      - pymeshfix==0.16.2
      - pymupdf==1.26.5
      - pyopencl==2026.1.2
      - pyparsing==3.3.1
      - pyside6==6.4.3
      - pyside6-addons==6.4.3
      - pyside6-essentials==6.4.3
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytools==2025.2.5
      - pytz==2025.2
      - pyvista==0.46.5
      - pywavelets==1.9.0
      - pyyaml==6.0.3
      - qtpy==2.4.3
      - requests==2.32.5
      - scikit-image==0.20.0
      - scooby==0.11.0
      - shiboken6==6.4.3
      - simpleitk==2.3.1
      - siphash24==1.8
      - six==1.17.0
      - superqt==0.7.7
      - tifffile==2026.1.14
      - trimesh==4.7.3
      - typing-extensions==4.15.0
      - uhi==1.0.0
      - urllib3==2.6.3
      - vtk==9.2.6
prefix: /home/spichardo/miniconda3/envs/Babel2
