name: Babel
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - altgraph=0.17.3=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-version=12.8=h30beaf8_3
  - cupy=13.6.0=py310h41781dc_0
  - cupy-core=13.6.0=py310h56f0b24_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=15_linux64_openblas
  - libcblas=3.9.0=15_linux64_openblas
  - libcublas=12.8.4.1=hbdd6827_1
  - libcufft=11.3.3.83=hbdd6827_1
  - libcurand=10.3.9.90=hbdd6827_1
  - libcusolver=11.7.3.90=hbdd6827_1
  - libcusparse=12.5.8.93=hbdd6827_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=11.2.0=h1234567_1
  - liblapack=3.9.0=15_linux64_openblas
  - libnvjitlink=12.8.93=hbdd6827_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.24.3=py310h375b286_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - pyinstaller=5.6.2=py310h5eee18b_0
  - pyinstaller-hooks-contrib=2023.1=pyhd8ed1ab_0
  - python=3.10.10=h7a1cb2a_2
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - sqlite=3.41.1=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - babelviscofdtd==1.2.3
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cffi==2.0.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - comm==0.2.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fastrlock==0.8.1
      - fonttools==4.39.3
      - fqdn==1.5.1
      - h11==0.16.0
      - h5py==3.8.0
      - hdf5plugin==4.1.1
      - histoprint==2.4.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.4
      - imageio==2.27.0
      - ipykernel==7.1.0
      - ipython==8.38.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kiwisolver==1.4.4
      - lark==1.3.1
      - lazy-loader==0.2
      - linetimer==0.1.5
      - llvmlite==0.39.1
      - manifold3d==3.2.1
      - markupsafe==3.0.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.0
      - nibabel==5.2.1
      - notebook-shim==0.2.4
      - numba==0.56.4
      - numpy==1.23.5
      - numpy-stl==3.0.1
      - openpyxl==3.1.5
      - overrides==7.7.0
      - packaging==23.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==9.4.0
      - platformdirs==3.2.0
      - pooch==1.7.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pwlf==2.5.1
      - pycparser==2.23
      - pydicom==2.3.1
      - pygments==2.14.0
      - pymeshfix==0.16.2
      - pymupdf==1.26.5
      - pyopencl==2022.3.1
      - pyparsing==3.0.9
      - pyside6==6.4.3
      - pyside6-addons==6.4.3
      - pyside6-essentials==6.4.3
      - python-dateutil==2.8.2
      - python-json-logger==4.0.0
      - python-utils==3.5.2
      - pytools==2022.1.14
      - pytz==2023.3
      - pyvista==0.38.5
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==27.1.0
      - qtpy==2.3.1
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - scikit-image==0.20.0
      - scipy==1.10.1
      - scooby==0.7.1
      - send2trash==2.1.0
      - shiboken6==6.4.3
      - simpleitk==2.3.1
      - six==1.16.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - superqt==0.4.1
      - terminado==0.18.1
      - tifffile==2023.3.21
      - tinycss2==1.4.0
      - tomli==2.4.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - trimesh==4.7.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - uhi==0.3.3
      - uri-template==1.3.0
      - urllib3==1.26.15
      - vtk==9.2.6
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - xmltodict==1.0.2
prefix: /home/spichardo/miniconda3/envs/Babel
