name: BabelBrain
channels:
  - defaults
dependencies:
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.30=hf2bb037_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - ncurses=6.5=hee39554_0
  - numpy=2.3.3=py311hc95ac1c_1
  - numpy-base=2.3.3=py311h8087a70_1
  - openssl=1.1.1w=h1a28f6b_0
  - pip=25.2=pyhc872135_1
  - python=3.11.0=hc0d8a6c_3
  - readline=8.3=h0b18652_0
  - scipy=1.16.2=py311h53ebd84_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - altgraph==0.17.4
      - babel==2.17.0
      - babelviscofdtd==1.1.5
      - backrefs==5.9
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - dict2xml==1.7.7
      - et-xmlfile==2.0.0
      - fonttools==4.60.1
      - ghp-import==2.1.0
      - h5py==3.15.1
      - hdf5plugin==6.0.0
      - histoprint==2.6.0
      - idna==3.11
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - latexcodec==3.0.1
      - lazy-loader==0.4
      - linetimer==0.1.5
      - llvmlite==0.45.1
      - macholib==1.16.3
      - manifold3d==3.2.1
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mergedeep==1.3.4
      - metalcomputebabel @ git+https://github.com/ProteusMRIgHIFU/py-metal-compute.git@75a6adb378a8155c9b6765df8626256f42216224
      - mkdocs==1.6.1
      - mkdocs-bibtex==4.4.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-gitbook==0.0.1
      - mkdocs-material==9.6.22
      - mkdocs-material-extensions==1.3.1
      - mkdocs-windmill==1.0.5
      - mlx @ git+https://github.com/spichardo/mlx.git@102e8fd398308fb05adea654ca21893d78a6b782
      - narwhals==2.9.0
      - networkx==3.5
      - nibabel==5.3.2
      - numba==0.62.1
      - numpy-stl==3.2.0
      - openpyxl==3.1.5
      - packaging==25.0
      - paginate==0.5.7
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.3.1
      - pluggy==1.6.0
      - pooch==1.8.2
      - pwlf==2.5.2
      - pybtex==0.25.1
      - pydicom==3.0.1
      - pygments==2.19.2
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.9
      - pymdown-extensions==10.16.1
      - pymeshfix==0.17.1
      - pymupdf==1.26.5
      - pyopencl==2025.2.6
      - pypandoc==1.15
      - pyparsing==3.2.5
      - pyside6==6.10.0
      - pyside6-addons==6.10.0
      - pyside6-essentials==6.10.0
      - pytest==8.4.2
      - pytest-html==4.1.1
      - pytest-metadata==3.1.1
      - pytest-qt==4.5.0
      - pytest-xml==0.1.1
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytools==2025.2.5
      - pytz==2025.2
      - pyvista==0.46.3
      - pyyaml==6.0.3
      - pyyaml-env-tag==1.1
      - qtpy==2.4.3
      - requests==2.32.5
      - responses==0.25.8
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scooby==0.10.2
      - shiboken6==6.10.0
      - simpleitk==2.5.2
      - siphash24==1.8
      - six==1.17.0
      - superqt==0.7.6
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - trimesh==4.9.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uhi==1.0.0
      - urllib3==2.5.0
      - validators==0.35.0
      - vtk==9.5.2
      - watchdog==6.0.0
prefix: /Users/spichardo/miniconda3/envs/Babel311
