### Site metadata ###

site_name: BabelBrain
site_description: BabelBrain 
site_url: https://proteusmrghifu.github.io/BabelBrain/
use_directory_urls: false

### Build settings ###
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    navigation_depth: 4

nav:
  - Home: index.md
  - Installation: installation.md
  - Overall pipeline : pipeline/pipeline.md
  - Preliminary steps: pipeline/Preliminary_steps.md
  - Planning: pipeline/Planning.md
  - BabelBrain simulation : pipeline/BabelBrain.md
  - MRI sequences : MRISequences/MRISequences.md
  - Results files : results/results.md
  - Advanced options: Advanced/advanced.md
  - Tx calibration: Advanced/TransducerCalibration.md
  - Appendix : Appendix/Appendix.md

markdown_extensions:
    - md4mathjax
    - footnotes
    - pymdownx.arithmatex

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
      csl_file: "the-journal-of-the-acoustical-society-of-america.csl"